### ISSUE TITLE
Should backend use django cors headers?

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-frontend#10]
As far as I know, there need to install django-cors-headers at backend because of cors header problem at frontend.
Is there any alternatives to avoid that problem? or we will install django-cors-headers to solve this condition and update codes at github.

**Comment by lameinthebox** [comment]
Well, I've found some suggestions; https://stackoverflow.com/a/43464387. It says the ideal way is to add CORS support to our server.

**Comment by holenet** [comment]
According to the answer you linked, the problem will be resolved on the deployment server machine, not development server.
Then, should we use django-cors-headers only on the development environment?

**Comment by lameinthebox** [comment]
I hope so.
Does current frontend works well when CORS is supported in backend?

**Comment by holenet** [comment]
close by merging corresponding pull request
