### ISSUE TITLE
How to implement that each Lecture has buttton?

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-frontend#14]
I tried to add button to each Lecture at `SearchLecture` molecule like this picture.
But I can't see button when I run frontend.
Do you know how to solve this problem?
![gnome-shell-screenshot-qtuyiz](https://user-images.githubusercontent.com/19183069/39963712-6d23880c-56ae-11e8-9b6b-e276cf4a5063.png)

**Comment by holenet** [comment]
####Possible solution
Wrap `Lecture` component and `Button` component with parentheses.

p.s. please use code block tag ` ``` ` of github markdown rather than uploading image, I cannot copy your code.

**Comment by holenet** [comment]
please set the language of the code.
I editted your comment and there is syntax highlighting now.

**Comment by holenet** [comment]
Don't use comma between React components, in this case, between `Lecture` and `Button`

**Comment by Tommybro** [comment]
If I remove comma, then I got error

**Comment by holenet** [comment]
What error? Specify it.

**Comment by Tommybro** [comment]
Error is this picture
![gnome-shell-screenshot-tu5piz](https://user-images.githubusercontent.com/19183069/39963895-0b9a1614-56b3-11e8-9366-2af58a4787d4.png)

**Comment by holenet** [comment]
Try wrapping two component with `<div>` tag.

**Comment by Tommybro** [comment]
Wow it works! Thanks~
