### ISSUE TITLE
What main color do you want for ttrs?

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-frontend#21]
Give me your opinion :)

**Comment by holenet** [comment]
RAINBOW!

**Comment by holenet** [comment]
How about this colors?
![image](https://user-images.githubusercontent.com/24453019/40580483-2634d208-617a-11e8-81ad-a15fa2f0639e.png)

**Comment by lameinthebox** [comment]
![screenshot from 2018-05-28 06-35-45](https://user-images.githubusercontent.com/19164119/40590850-6731ffca-6241-11e8-9582-ba088e15a800.png)

**Comment by Tommybro** [comment]
초록 계열 이쁜듯 초록 계열로 합시다~
