### ISSUE TITLE
Choose UI Library for the frontend design

### ISSUE THREAD

**Issue by holenet** [SWPP/ttrs-frontend#22]
I think we should use some library for the design.
Please choose a library that seems good.
## 1. [Material-UI](https://material-ui.com/)
> React components that implement Google's Material Design.

This library is based on [Google's Meterial Design](https://material.io/design/introduction/)
If we use this library, it is expected to get a result like this,
![image](https://user-images.githubusercontent.com/24453019/40580752-77173192-6180-11e8-83a2-81e85ed07169.png)
**Yes**, it is just like an _android_ app.
If we target the mobile users, it would be better to use this approach.
## 2. [Semantic UI](https://semantic-ui.com/)
> Design Beautiful Websites Quickly
Semantic is a development framework that helps create beautiful, responsive layouts using human-friendly HTML.

This library seems more general than Material-UI. It means, we can customize more flexibly.
We can gain a result like this,
![image](https://user-images.githubusercontent.com/24453019/40580773-071d9d76-6181-11e8-932d-64acbcf26450.png)
If we use this library, we can use it for react app, [here](https://react.semantic-ui.com).

**Comment by lameinthebox** [comment]
Semantic UI :+1:

**Comment by Tommybro** [comment]
Lets use Semantic UI

**Comment by holenet** [comment]
@tommybro
Why do you think so?

**Comment by Tommybro** [comment]
It seems easier to use Semantic UI

**Comment by holenet** [comment]
Close with using Semantic UI.
