### ISSUE TITLE
Please fix bug about TimeTable

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-frontend#26]
@lameinthebox 

When a lecture have timeSlots that have same startTime, our timeTable doesn't work well.
Now, timeSlots that have same startTime merges their height.
They should not merge their height and their should be one timeSlot for timeSlots that have same startTime.

**Comment by lameinthebox** [comment]
Ok. I'll go check.

**Comment by lameinthebox** [comment]
Closing issue as the corresponding code is refactored.
